# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, interpolatedstringPerl6, lens, split, text, wreq
, yesod
}:

cabal.mkDerivation (self: {
  pname = "lr-yesod";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    aeson interpolatedstringPerl6 lens split text wreq yesod
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
